name: Protect Main and Dev Branches

on:
  push:
    branches:
      - main
      - dev

jobs:
  block-direct-push:
    name: Block Direct Push to Main/Dev
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Block Push to Protected Branches
        run: |
          echo "❌ Direct push to protected branches is not allowed!"
          echo "Please create a Pull Request to update these branches."
          exit 1