name: Protect Branches
on:
  push:
    branches:
      - main
      - dev

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check push type
        run: |
          IS_MERGE=$(git log -1 --pretty=%P ${{ github.sha }} | wc -w)

          COMMIT_MSG=$(git log -1 --pretty=%B ${{ github.sha }})

          if [[ "$IS_MERGE" == "2" ]] || [[ "$COMMIT_MSG" =~ ^merge: ]] || [[ "${{ github.event.ref }}" == "refs/heads/dev" && "${{ github.event_name }}" == "pull_request" ]]; then
            echo "✅ Merge commit or PR merge detected, allowing the push"
            exit 0
          else
            echo "❌ Direct push to protected branches is not allowed!"
            echo "Please create a Pull Request to update these branches."
            exit 1
          fi