name: PR Telegram Notification

on:
  pull_request:
    types: [opened, closed, edited, ready_for_review, review_requested, reopened]
  pull_request_review:
    types: [submitted, edited, dismissed]
  pull_request_review_comment:
    types: [created, edited, deleted]
  issues:
    types: [opened, closed, reopened, edited]
  issue_comment:
    types: [created, edited, deleted]
  fork:
  push:
    branches:
      - main
      - dev
      - 'release/**'
      - 'feature/**'
      - 'hotfix/**'
      - 'bugfix/**'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: html
          disable_web_page_preview: true
          message: |
            🔔 GitHub Notification
            
            📝 Pull Request 
            ├─ Branch Soucer: ${{ github.event.pull_request.head.ref }}
            ├─ Branch Target: ${{ github.event.pull_request.base.ref }}
            ├─ Author: ${{ github.event.pull_request.user.login }} (https://github.com/${{ github.event.pull_request.user.login }})
            └─ Last Commit:
            ${{ github.event.pull_request.title }}
            └─ View Commit (https://github.com/${{ github.repository }}/commit/${{ github.event.pull_request.head.sha }})
            └─ View Pull Request (https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }})

            ⏰ ${{ github.event.pull_request.updated_at }}
