name: PR Telegram Notification

on:
  pull_request:
    types: [opened, closed, edited, ready_for_review, review_requested, reopened]
  pull_request_review:
    types: [submitted, edited, dismissed]
  pull_request_review_comment:
    types: [created, edited, deleted]
  issues:
    types: [opened, closed, reopened, edited]
  issue_comment:
    types: [created, edited, deleted]
  fork:
  push:
    branches:
      - main
      - dev
      - 'release/**'
      - 'feature/**'
      - 'hotfix/**'
      - 'bugfix/**'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Get current UTC time
        id: current-time
        run: echo "::set-output name=time::$(date -u '+%d/%m/%Y %H:%M:%S UTC')"

      - name: Send Telegram Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            🔔 *GitHub Activity*
            
            ${{ github.event_name == 'pull_request' && format('*PR #{0}: {1}*
            ↳ Status: {2}
            ↳ Branch: `{3}` → `{4}`
            ↳ By: [{5}]({6})
            ↳ Commits: {7}
            ↳ [View #{8}]({9})', 
            github.event.pull_request.number,
            github.event.pull_request.title,
            github.event.pull_request.state,
            github.event.pull_request.head.ref,
            github.event.pull_request.base.ref,
            github.event.pull_request.user.login,
            github.event.pull_request.user.html_url,
            github.event.pull_request.commits,
            github.event.pull_request.number,
            github.event.pull_request.html_url) || '' }}
            
            ${{ github.event_name == 'push' && format('*Push to* `{0}`
            ↳ By: [{1}](https://github.com/{1})
            ↳ [View Changes]({2}/commit/{3})
            ↳ [Pull Request #{4}]({2}/pull/{4})

            {5}', 
            github.ref_name,
            github.event.pusher.name,
            github.event.repository.html_url,
            github.event.after,
            replace(github.event.head_commit.message, '.*Part of #([0-9]+).*', '$1'),
            github.event.head_commit.message) || '' }}
            
            ${{ github.event_name == 'issues' && format('*Issue #{0}: {1}*
            ↳ Status: {2}
            ↳ By: [{3}]({4})
            ↳ [View #{5}]({6})', 
            github.event.issue.number,
            github.event.issue.title,
            github.event.action,
            github.event.issue.user.login,
            github.event.issue.user.html_url,
            github.event.issue.number,
            github.event.issue.html_url) || '' }}
            
            ⏰ _${{ steps.current-time.outputs.time }}_
