name: PR Telegram Notification

on:
  pull_request:
    types: [opened, closed, edited, ready_for_review, review_requested, reopened]
  pull_request_review:
    types: [submitted, edited, dismissed]
  pull_request_review_comment:
    types: [created, edited, deleted]
  issues:
    types: [opened, closed, reopened, edited]
  issue_comment:
    types: [created, edited, deleted]
  fork:
  push:
    branches:
      - main
      - dev
      - 'release/**'
      - 'feature/**'
      - 'hotfix/**'
      - 'bugfix/**'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            🔔 *GitHub Notification*
            
            *Repository:* [${{ github.repository }}](https://github.com/${{ github.repository }})
            
            ${{ github.event_name == 'pull_request' && format('🔄 *Pull Request #{0}*
            └ *Title:* {1}
            └ *Status:* {2}
            └ *Author:* [{3}]({4})
            └ [View PR]({5})', 
            github.event.pull_request.number,
            github.event.pull_request.title,
            github.event.action,
            github.event.pull_request.user.login,
            github.event.pull_request.user.html_url,
            github.event.pull_request.html_url) || '' }}
            
            ${{ github.event_name == 'push' && format('📦 *New Push*
            └ *Branch:* `{0}`
            └ *Author:* {1}
            └ *Commits:* {2}', 
            github.ref_name,
            github.event.pusher.name,
            github.event.commits.length) || '' }}
            
            ${{ github.event_name == 'fork' && format('🔱 *Repository Forked*
            └ *By:* [{0}]({1})', 
            github.event.forkee.owner.login,
            github.event.forkee.owner.html_url) || '' }}
            
            ${{ github.event_name == 'issues' && format('📌 *Issue #{0}*
            └ *Title:* {1}
            └ *Action:* {2}
            └ [View Issue]({3})', 
            github.event.issue.number,
            github.event.issue.title,
            github.event.action,
            github.event.issue.html_url) || '' }}
