name: PR Telegram Notification

on:
  pull_request:
    types: [opened, closed, edited, ready_for_review, review_requested, reopened]
  pull_request_review:
    types: [submitted, edited, dismissed]
  pull_request_review_comment:
    types: [created, edited, deleted]
  issues:
    types: [opened, closed, reopened, edited]
  issue_comment:
    types: [created, edited, deleted]
  fork:
  push:
    branches:
      - main
      - dev
      - 'release/**'
      - 'feature/**'
      - 'hotfix/**'
      - 'bugfix/**'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Get current UTC time
        id: current-time
        run: echo "::set-output name=time::$(date -u '+%d/%m/%Y %H:%M:%S UTC')"

      - name: Send Telegram Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            📣 *GitHub Activity Notification*
            [${{ github.repository }}](https://github.com/${{ github.repository }})
            
            ${{ github.event_name == 'pull_request' && format('🔄 *Pull Request #{0}*
            └ *Title:* {1}
            └ *Status:* {2}
            └ *Developer:* [{3}]({4})
            └ *Source Branch:* `{5}`
            └ *Target Branch:* `{6}`
            └ *Total Commits:* {7}
            └ *Labels:* {8}
            └ [View PR]({9})

            *Description:*
            ```
            {10}
            ```', 
            github.event.pull_request.number,
            github.event.pull_request.title,
            github.event.action,
            github.event.pull_request.user.login,
            github.event.pull_request.user.html_url,
            github.event.pull_request.head.ref,
            github.event.pull_request.base.ref,
            github.event.pull_request.commits,
            join(github.event.pull_request.labels.*.name, ', '),
            github.event.pull_request.html_url,
            github.event.pull_request.body || 'No description provided') || '' }}
            
            ${{ github.event_name == 'push' && format('📦 *Code Push Details*
            └ *Source Branch:* `{0}`
            └ *Target Branch:* `{1}`
            └ *Developer:* [{2}](https://github.com/{2})
            └ *Total Commits:* {3}
            └ [View Changes]({4}/commit/{5})

            *Latest Commit Message:*
            ```
            {6}
            ```', 
            github.event.ref,
            github.event.base_ref || github.event.ref,
            github.event.pusher.name,
            github.event.commits.length,
            github.event.repository.html_url,
            github.event.after,
            github.event.head_commit.message) || '' }}
            
            ${{ github.event_name == 'issues' && format('📌 *Issue #{0}*
            └ *Title:* {1}
            └ *Status:* {2}
            └ *Created by:* [{3}]({4})
            └ *Labels:* {5}
            └ [View Issue]({6})

            *Description:*
            ```
            {7}
            ```', 
            github.event.issue.number,
            github.event.issue.title,
            github.event.action,
            github.event.issue.user.login,
            github.event.issue.user.html_url,
            join(github.event.issue.labels.*.name, ', '),
            github.event.issue.html_url,
            github.event.issue.body || 'No description provided') || '' }}
            
            ⏰ _${{ steps.current-time.outputs.time }}_
