name: PR Telegram Notification

on:
  pull_request:
    types: [opened, closed, edited, ready_for_review, review_requested, reopened]
  pull_request_review:
    types: [submitted, edited, dismissed]
  pull_request_review_comment:
    types: [created, edited, deleted]
  push:
    branches:
      - main
      - dev
      - 'release/**'
      - 'feature/**'
      - 'hotfix/**'
      - 'bugfix/**'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Get current UTC time
        id: current-time
        run: echo "time=$(date -u '+%d/%m/%Y %H:%M:%S UTC')" >> $GITHUB_ENV

      - name: Prepare Telegram Notification Message
        id: prepare-message
        run: |
          MESSAGE=""
          
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            PR_NUMBER="${{ github.event.pull_request.number }}"
            PR_TITLE="${{ github.event.pull_request.title }}"
            PR_STATE="${{ github.event.pull_request.state }}"
            SOURCE_BRANCH="${{ github.event.pull_request.head.ref }}"
            TARGET_BRANCH="${{ github.event.pull_request.base.ref }}"
            AUTHOR="${{ github.event.pull_request.user.login }}"
            AUTHOR_URL="${{ github.event.pull_request.user.html_url }}"
            LAST_COMMIT="${{ github.event.pull_request.head.sha }}"
            REPO_URL="${{ github.event.repository.html_url }}"
            PR_URL="${{ github.event.pull_request.html_url }}"
            
            MESSAGE="🔔 *GitHub Notification*\n\n"
            MESSAGE+="📝 *Pull Request*\n"
            MESSAGE+="├─ *Branch Source:* \`${SOURCE_BRANCH}\`\n"
            MESSAGE+="├─ *Branch Target:* \`${TARGET_BRANCH}\`\n"
            MESSAGE+="├─ *Author:* [${AUTHOR}](${AUTHOR_URL})\n"
            MESSAGE+="└─ *Last Commit:*\n"
            MESSAGE+="\`${{ github.event.pull_request.head.commit.message }}\`\n"
            MESSAGE+="└─ [View Commit](${REPO_URL}/commit/${LAST_COMMIT})\n"
            MESSAGE+="└─ [View Pull Request](${PR_URL})\n"
            MESSAGE+="\n⏰ _${{ env.time }}_"
          
          elif [[ "${{ github.event_name }}" == "push" ]]; then
            BRANCH="${{ github.ref_name }}"
            AUTHOR="${{ github.event.pusher.name }}"
            LAST_COMMIT="${{ github.event.after }}"
            REPO_URL="${{ github.event.repository.html_url }}"
            COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
            
            MESSAGE="🔔 *GitHub Notification*\n\n"
            MESSAGE+="📝 *New Changes*\n"
            MESSAGE+="├─ *Branch:* \`${BRANCH}\`\n"
            MESSAGE+="├─ *Author:* [${AUTHOR}](${REPO_URL})\n"
            MESSAGE+="└─ [View Commit](${REPO_URL}/commit/${LAST_COMMIT})\n"
            MESSAGE+="\n\`\`\`\n${COMMIT_MESSAGE}\n\`\`\`\n"
            MESSAGE+="\n⏰ _${{ env.time }}_"
          fi

          echo "message=$MESSAGE" >> $GITHUB_ENV

      - name: Send Telegram Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: ${{ env.message }}
