name: PR Telegram Notification

on:
  pull_request:
    types: [opened, closed, edited, ready_for_review, review_requested, reopened]
  pull_request_review:
    types: [submitted, edited, dismissed]
  pull_request_review_comment:
    types: [created, edited, deleted]
  issues:
    types: [opened, closed, reopened, edited]
  issue_comment:
    types: [created, edited, deleted]
  fork:
  push:
    branches:
      - main
      - dev
      - 'release/**'
      - 'feature/**'
      - 'hotfix/**'
      - 'bugfix/**'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            🔔 *GitHub Notification*
            
            *Repository:* [${{ github.repository }}](https://github.com/${{ github.repository }})
            *Branch:* `${{ github.ref_name }}`
            
            ${{ github.event_name == 'pull_request' && format('🔄 *Pull Request #{0}*
            └ *Title:* {1}
            └ *Status:* {2}
            └ *Author:* [{3}]({4})
            └ *Base Branch:* `{5}`
            └ *Labels:* {6}
            └ [View PR]({7})', 
            github.event.pull_request.number,
            github.event.pull_request.title,
            github.event.action,
            github.event.pull_request.user.login,
            github.event.pull_request.user.html_url,
            github.event.pull_request.base.ref,
            join(github.event.pull_request.labels.*.name, ', '),
            github.event.pull_request.html_url) || '' }}
            
            ${{ github.event_name == 'push' && format('📦 *New Push*
            └ *Branch:* `{0}`
            └ *Author:* [{1}](https://github.com/{1})
            └ *Commits:* {2}
            └ [View Changes]({3})

            *Latest Commit Details:*
            ```
            {4}
            ```
            
            *Commit Hash:* `{5}`', 
            github.ref_name,
            github.event.pusher.name,
            github.event.commits.length,
            format('{0}/commit/{1}', github.event.repository.html_url, github.event.after),
            github.event.head_commit.message,
            github.event.after.substring(0, 7)) || '' }}
            
            ${{ github.event_name == 'fork' && format('🔱 *Repository Forked*
            └ *By:* [{0}]({1})
            └ *Fork Name:* {2}
            └ [View Fork]({3})', 
            github.event.forkee.owner.login,
            github.event.forkee.owner.html_url,
            github.event.forkee.full_name,
            github.event.forkee.html_url) || '' }}
            
            ${{ github.event_name == 'issues' && format('📌 *Issue #{0}*
            └ *Title:* {1}
            └ *Status:* {2}
            └ *Author:* [{3}]({4})
            └ *Labels:* {5}
            └ [View Issue]({6})', 
            github.event.issue.number,
            github.event.issue.title,
            github.event.action,
            github.event.issue.user.login,
            github.event.issue.user.html_url,
            join(github.event.issue.labels.*.name, ', '),
            github.event.issue.html_url) || '' }}
            
            ⏰ _${{ github.event.repository.updated_at }}_
