name: Qodana Analysis

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches-ignore:
      - 'automation/*'
  push:
    branches:
      - main
      - dev
      - 'release/*'
      - 'feature/*'
      - 'hotfix/*'
      - 'bugfix/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Qodana Scan
        uses: JetBrains/qodana-action@v2023.3
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_1403575179 }}
        with:
          args: --baseline,qodana.sarif.json --apply-fixes --fail-threshold=3
          results-dir: ${{ runner.temp }}/qodana/results
          upload-result: true
          pr-mode: true
          use-annotations: true

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: qodana-report
          path: ${{ runner.temp }}/qodana/results/report/**
          if-no-files-found: warn

      - name: Upload SARIF to GitHub Security
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
          wait-for-processing: true