name: Qodana Quality Check

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - dev
      - 'release/*'
      - 'feature/*'
      - 'hotfix/*'
      - 'bugfix/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
      security-events: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Setup .NET Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
    
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

            
      
      - name: Define Fix Branch Name
        id: branch-name
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          SOURCE_BRANCH=${{ github.event.pull_request.head.ref }}
          BRANCH_TYPE=$(echo "$SOURCE_BRANCH" | cut -d'/' -f1)
          
          if [[ -n "$PR_NUMBER" ]]; then
            FIXES_BRANCH="${BRANCH_TYPE}/qodana-${PR_NUMBER}"
          else
            FIXES_BRANCH="fix/qodana-$(date +%Y%m%d%H%M%S)"
          fi
          echo "FIXES_BRANCH=${FIXES_BRANCH}" >> $GITHUB_ENV
          echo "SOURCE_BRANCH=${SOURCE_BRANCH}" >> $GITHUB_ENV

            
      
      - name: Run Qodana Analysis
        uses: JetBrains/qodana-action@v2024.2
        with:
          args: --baseline,qodana.sarif.json --apply-fixes
          push-fixes: pull-request
          fail-threshold: 3
          post-pr-comment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          use-caches: true
          cache-default-branch-only: true
          upload-result: true
          artifact-name: qodana-results
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          QODANA_ENDPOINT: 'https://qodana.cloud'

            
      
      - name: Apply Fixes and Format Code
        if: steps.qodana.outputs.has-fixes == 'true'
        run: |
          git checkout $SOURCE_BRANCH
          git checkout -b $FIXES_BRANCH
    
          dotnet tool install -g csharpier
          dotnet csharpier .

          git add .
          if [[ -z "$(git status --porcelain)" ]]; then
            echo "No changes to commit."
            exit 0
          fi
          
                 
       
          case "$BRANCH_TYPE" in
            "feature") COMMIT_TYPE="fix" ;;
            "hotfix") COMMIT_TYPE="hotfix" ;;
            "bugfix") COMMIT_TYPE="bugfix" ;;
            "release") COMMIT_TYPE="chore" ;;
            *) COMMIT_TYPE="fix" ;;
          esac
          git commit -m "${COMMIT_TYPE}(qodana): apply code quality fixes

          - Applied Qodana suggested fixes
          - Formatted code with CSharpier
          - Improved code quality"
          git push origin $FIXES_BRANCH

             
       
      - name: Create Pull Request
        if: steps.qodana.outputs.has-fixes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "${{ env.BRANCH_TYPE }}(qodana): apply code quality improvements"
          body: |
            🤖 Automated PR created by Qodana
            
            This PR includes:
            - Qodana automated fixes
            - CSharpier code formatting
            - Code quality improvements
            
            Please review the changes and merge if appropriate.
          branch: ${{ env.FIXES_BRANCH }}
          base: ${{ env.SOURCE_BRANCH }}
          labels: qodana,automated-pr,code-quality

          
    
      - name: Upload Qodana SARIF
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
