name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: 
      - main 
      - dev
      - 'release/*' 
      - 'feature/*'
      - 'hotfix/*'
jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
      security-events: write  
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.2
        with:
          args: --baseline,qodana.sarif.json --apply-fixes
          push-fixes: pull-request
          fail-threshold: 3
          post-pr-comment: true
          use-caches: true
          cache-default-branch-only: true
          upload-result: true
          artifact-name: qodana-results
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_1403575179 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json