name: Qodana Analysis

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - dev
      - 'release/*'
      - 'feature/*'
      - 'hotfix/*'
      - 'bugfix/*'
    branches-ignore:
      - 'automation/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        linter:
          - dotnet
          - js
          - sql
        version:
          - 2024.2

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Qodana
        uses: JetBrains/qodana-action@v2024.2
        with:
          args: |
            --baseline,qodana.sarif.json
            --apply-fixes
            --fail-threshold=3
          linter: jetbrains/qodana-${{ matrix.linter }}:${{ matrix.version }}
          upload-result: true
          artifact-name: qodana-${{ matrix.linter }}-results
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_1403575179 }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: qodana-html-${{ matrix.linter }}
          path: .qodana/results/report.html

      - name: Annotate Code with Qodana
        if: always()
        uses: JetBrains/qodana-action@v2024.2
        with:
          use-annotations: true

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
